default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || '155339491ea30e80a492d54e1c48de18' %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] || '887384617053-2uma1e2774m4c1vu897jh2453k5lrfqv.apps.googleusercontent.com' %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] || '62ELszU4pePg-9N69Nah_AVc' %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
